# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  install-aws-cli:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip3 install awscli
  
  configure-aws-iam-profile:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - run:
          name: Configure AWS IAM Profile
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set region ${AWS_DEFAULT_REGION}
  
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region ${AWS_DEFAULT_REGION}

workflows:
  my-workflow:
    jobs:
      - install-aws-cli
      - configure-aws-iam-profile:
          requires:
            - install-aws-cli
      - create_infrastructure:
          requires:
            - configure-aws-iam-profile